FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env

RUN sed -i 's/\[openssl_init\]/# [openssl_init]/' /etc/ssl/openssl.cnf &&\
    printf "\n\n[openssl_init]\nssl_conf = ssl_sect" >> /etc/ssl/openssl.cnf &&\
    printf "\n\n[ssl_sect]\nsystem_default = ssl_default_sect" >> /etc/ssl/openssl.cnf &&\
    printf "\n\n[ssl_default_sect]\nMinProtocol = TLSv1\nCipherString = DEFAULT@SECLEVEL=0\n" >> /etc/ssl/openssl.cnf

RUN apt-get update && apt-get install -y --no-install-recommends curl

WORKDIR /app

COPY Gnoss.Web.Intern/*.csproj ./

RUN dotnet restore

COPY . ./

RUN dotnet publish Gnoss.Web.Intern/Gnoss.Web.Intern.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0

RUN sed -i 's/\[openssl_init\]/# [openssl_init]/' /etc/ssl/openssl.cnf &&\
    printf "\n\n[openssl_init]\nssl_conf = ssl_sect" >> /etc/ssl/openssl.cnf &&\
    printf "\n\n[ssl_sect]\nsystem_default = ssl_default_sect" >> /etc/ssl/openssl.cnf &&\
    printf "\n\n[ssl_default_sect]\nMinProtocol = TLSv1\nCipherString = DEFAULT@SECLEVEL=0\n" >> /etc/ssl/openssl.cnf

ENV DOTNET_USE_POLLING_FILE_WATCHER=true

RUN apt-get update && apt-get install -y --no-install-recommends curl

RUN apt-get install -y unzip

RUN apt-get install -y zip

WORKDIR /app
RUN groupadd -g 1000 gnoss && useradd -u 1000 -g 1000 gnoss &&\
	mkdir -p logs trazas doclinks imagenes imagenesEnlaces Videos temporales &&\
	chown -R gnoss:gnoss logs trazas doclinks imagenes imagenesEnlaces Videos temporales &&\
	chmod -R 777 logs trazas doclinks imagenes imagenesEnlaces Videos temporales
USER gnoss

COPY --from=build-env /app/out .

ENTRYPOINT ["dotnet", "Gnoss.Web.Intern.dll"]
