<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<UserSecretsId>4fee1e2b-f47c-4a22-8eea-6c2f42410932</UserSecretsId>
		<DockerDefaultTargetOS>Windows</DockerDefaultTargetOS>
		<DockerfileContext>.</DockerfileContext>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<ServerGarbageCollection>false</ServerGarbageCollection>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.7" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Systemd" Version="10.0.7" />
		<PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.7" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
		<PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="10.1.7" />
		<PackageReference Include="Swashbuckle.AspNetCore.Filters" Version="10.0.1" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Gnoss.Commons\Es.Riam.Gnoss.AD\Es.Riam.Gnoss.AD.csproj" />
    <ProjectReference Include="..\..\Gnoss.Commons\Es.Riam.Gnoss.FileManager\Es.Riam.Gnoss.FileManager.csproj" />
    <ProjectReference Include="..\..\Gnoss.Commons\Es.Riam.Gnoss.Logica\Es.Riam.Gnoss.Logica.csproj" />
    <ProjectReference Include="..\..\Gnoss.Commons\Es.Riam.Gnoss.Web.Controles\Es.Riam.Gnoss.Web.Controles.csproj" />
    <ProjectReference Include="..\..\Gnoss.Commons\Es.Riam.OpenArchivos\Es.Riam.OpenArchivos.csproj" />
    <ProjectReference Include="..\..\Gnoss.Commons\Es.Riam.OpenReplication\Es.Riam.OpenReplication.csproj" />
	<ProjectReference Include="..\..\Gnoss.Commons\Es.Riam.InterfacesOpen\Es.Riam.InterfacesOpen.csproj" />
	<ProjectReference Include="..\..\Gnoss.Commons\Es.Riam.Open\Es.Riam.Open.csproj" />
    <ProjectReference Include="..\..\Gnoss.Commons\Es.Riam.Util\Es.Riam.Util.csproj" />
    <ProjectReference Include="..\..\Gnoss.Commons\Es.Riam.Web.Util\Es.Riam.Web.Util.csproj" />
	<ProjectReference Include="..\..\Gnoss.Commons\Es.Riam.Gnoss.HealthChecks\Es.Riam.Gnoss.HealthChecks.csproj" />
  </ItemGroup>

  <ProjectExtensions><VisualStudio><UserProperties appsettings_1json__JsonSchema="" /></VisualStudio></ProjectExtensions>

</Project>
